// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smdbrpc/protos/smdbrpc.proto

package execinfrapb

/*
	package cockroach.sql.distsqlrun;
*/

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type HLCTimestamp struct {
	Walltime    *int64 `protobuf:"varint,1,opt,name=walltime" json:"walltime,omitempty"`
	Logicaltime *int32 `protobuf:"varint,2,opt,name=logicaltime" json:"logicaltime,omitempty"`
}

func (m *HLCTimestamp) Reset()         { *m = HLCTimestamp{} }
func (m *HLCTimestamp) String() string { return proto.CompactTextString(m) }
func (*HLCTimestamp) ProtoMessage()    {}
func (*HLCTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_smdbrpc_ab625d982200c379, []int{0}
}
func (m *HLCTimestamp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HLCTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *HLCTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HLCTimestamp.Merge(dst, src)
}
func (m *HLCTimestamp) XXX_Size() int {
	return m.Size()
}
func (m *HLCTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_HLCTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_HLCTimestamp proto.InternalMessageInfo

type KVPair struct {
	Key   *uint64 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Value *uint64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *KVPair) Reset()         { *m = KVPair{} }
func (m *KVPair) String() string { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()    {}
func (*KVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_smdbrpc_ab625d982200c379, []int{1}
}
func (m *KVPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *KVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVPair.Merge(dst, src)
}
func (m *KVPair) XXX_Size() int {
	return m.Size()
}
func (m *KVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KVPair.DiscardUnknown(m)
}

var xxx_messageInfo_KVPair proto.InternalMessageInfo

type HotshardRequest struct {
	Hlctimestamp *HLCTimestamp `protobuf:"bytes,1,opt,name=hlctimestamp" json:"hlctimestamp,omitempty"`
	WriteKeyset  []*KVPair     `protobuf:"bytes,2,rep,name=write_keyset,json=writeKeyset" json:"write_keyset,omitempty"`
	ReadKeyset   []uint64      `protobuf:"varint,3,rep,name=read_keyset,json=readKeyset" json:"read_keyset,omitempty"`
}

func (m *HotshardRequest) Reset()         { *m = HotshardRequest{} }
func (m *HotshardRequest) String() string { return proto.CompactTextString(m) }
func (*HotshardRequest) ProtoMessage()    {}
func (*HotshardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_smdbrpc_ab625d982200c379, []int{2}
}
func (m *HotshardRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HotshardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *HotshardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotshardRequest.Merge(dst, src)
}
func (m *HotshardRequest) XXX_Size() int {
	return m.Size()
}
func (m *HotshardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HotshardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HotshardRequest proto.InternalMessageInfo

// The response message containing the greetings
type HotshardReply struct {
	IsCommitted  *bool     `protobuf:"varint,1,opt,name=is_committed,json=isCommitted" json:"is_committed,omitempty"`
	ReadValueset []*KVPair `protobuf:"bytes,2,rep,name=read_valueset,json=readValueset" json:"read_valueset,omitempty"`
}

func (m *HotshardReply) Reset()         { *m = HotshardReply{} }
func (m *HotshardReply) String() string { return proto.CompactTextString(m) }
func (*HotshardReply) ProtoMessage()    {}
func (*HotshardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_smdbrpc_ab625d982200c379, []int{3}
}
func (m *HotshardReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HotshardReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *HotshardReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotshardReply.Merge(dst, src)
}
func (m *HotshardReply) XXX_Size() int {
	return m.Size()
}
func (m *HotshardReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HotshardReply.DiscardUnknown(m)
}

var xxx_messageInfo_HotshardReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HLCTimestamp)(nil), "smdbrpc.HLCTimestamp")
	proto.RegisterType((*KVPair)(nil), "smdbrpc.KVPair")
	proto.RegisterType((*HotshardRequest)(nil), "smdbrpc.HotshardRequest")
	proto.RegisterType((*HotshardReply)(nil), "smdbrpc.HotshardReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HotshardGatewayClient is the client API for HotshardGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HotshardGatewayClient interface {
	// Sends a greeting
	ContactHotshard(ctx context.Context, in *HotshardRequest, opts ...grpc.CallOption) (*HotshardReply, error)
}

type hotshardGatewayClient struct {
	cc *grpc.ClientConn
}

func NewHotshardGatewayClient(cc *grpc.ClientConn) HotshardGatewayClient {
	return &hotshardGatewayClient{cc}
}

func (c *hotshardGatewayClient) ContactHotshard(ctx context.Context, in *HotshardRequest, opts ...grpc.CallOption) (*HotshardReply, error) {
	out := new(HotshardReply)
	err := c.cc.Invoke(ctx, "/smdbrpc.HotshardGateway/ContactHotshard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotshardGatewayServer is the server API for HotshardGateway service.
type HotshardGatewayServer interface {
	// Sends a greeting
	ContactHotshard(context.Context, *HotshardRequest) (*HotshardReply, error)
}

func RegisterHotshardGatewayServer(s *grpc.Server, srv HotshardGatewayServer) {
	s.RegisterService(&_HotshardGateway_serviceDesc, srv)
}

func _HotshardGateway_ContactHotshard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotshardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotshardGatewayServer).ContactHotshard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smdbrpc.HotshardGateway/ContactHotshard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotshardGatewayServer).ContactHotshard(ctx, req.(*HotshardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HotshardGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smdbrpc.HotshardGateway",
	HandlerType: (*HotshardGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContactHotshard",
			Handler:    _HotshardGateway_ContactHotshard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smdbrpc/protos/smdbrpc.proto",
}

func (m *HLCTimestamp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HLCTimestamp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Walltime != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSmdbrpc(dAtA, i, uint64(*m.Walltime))
	}
	if m.Logicaltime != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSmdbrpc(dAtA, i, uint64(*m.Logicaltime))
	}
	return i, nil
}

func (m *KVPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVPair) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Key != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSmdbrpc(dAtA, i, uint64(*m.Key))
	}
	if m.Value != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSmdbrpc(dAtA, i, uint64(*m.Value))
	}
	return i, nil
}

func (m *HotshardRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HotshardRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Hlctimestamp != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSmdbrpc(dAtA, i, uint64(m.Hlctimestamp.Size()))
		n1, err := m.Hlctimestamp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.WriteKeyset) > 0 {
		for _, msg := range m.WriteKeyset {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSmdbrpc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ReadKeyset) > 0 {
		for _, num := range m.ReadKeyset {
			dAtA[i] = 0x18
			i++
			i = encodeVarintSmdbrpc(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *HotshardReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HotshardReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IsCommitted != nil {
		dAtA[i] = 0x8
		i++
		if *m.IsCommitted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.ReadValueset) > 0 {
		for _, msg := range m.ReadValueset {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSmdbrpc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintSmdbrpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *HLCTimestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Walltime != nil {
		n += 1 + sovSmdbrpc(uint64(*m.Walltime))
	}
	if m.Logicaltime != nil {
		n += 1 + sovSmdbrpc(uint64(*m.Logicaltime))
	}
	return n
}

func (m *KVPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Key != nil {
		n += 1 + sovSmdbrpc(uint64(*m.Key))
	}
	if m.Value != nil {
		n += 1 + sovSmdbrpc(uint64(*m.Value))
	}
	return n
}

func (m *HotshardRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Hlctimestamp != nil {
		l = m.Hlctimestamp.Size()
		n += 1 + l + sovSmdbrpc(uint64(l))
	}
	if len(m.WriteKeyset) > 0 {
		for _, e := range m.WriteKeyset {
			l = e.Size()
			n += 1 + l + sovSmdbrpc(uint64(l))
		}
	}
	if len(m.ReadKeyset) > 0 {
		for _, e := range m.ReadKeyset {
			n += 1 + sovSmdbrpc(uint64(e))
		}
	}
	return n
}

func (m *HotshardReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsCommitted != nil {
		n += 2
	}
	if len(m.ReadValueset) > 0 {
		for _, e := range m.ReadValueset {
			l = e.Size()
			n += 1 + l + sovSmdbrpc(uint64(l))
		}
	}
	return n
}

func sovSmdbrpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSmdbrpc(x uint64) (n int) {
	return sovSmdbrpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HLCTimestamp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSmdbrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HLCTimestamp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HLCTimestamp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Walltime", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Walltime = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logicaltime", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Logicaltime = &v
		default:
			iNdEx = preIndex
			skippy, err := skipSmdbrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSmdbrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Key = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Value = &v
		default:
			iNdEx = preIndex
			skippy, err := skipSmdbrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HotshardRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSmdbrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HotshardRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HotshardRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hlctimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Hlctimestamp == nil {
				m.Hlctimestamp = &HLCTimestamp{}
			}
			if err := m.Hlctimestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriteKeyset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriteKeyset = append(m.WriteKeyset, &KVPair{})
			if err := m.WriteKeyset[len(m.WriteKeyset)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSmdbrpc
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReadKeyset = append(m.ReadKeyset, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSmdbrpc
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSmdbrpc
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReadKeyset) == 0 {
					m.ReadKeyset = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSmdbrpc
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReadKeyset = append(m.ReadKeyset, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadKeyset", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSmdbrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HotshardReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSmdbrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HotshardReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HotshardReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsCommitted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.IsCommitted = &b
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadValueset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadValueset = append(m.ReadValueset, &KVPair{})
			if err := m.ReadValueset[len(m.ReadValueset)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSmdbrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSmdbrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSmdbrpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSmdbrpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSmdbrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSmdbrpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSmdbrpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSmdbrpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSmdbrpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSmdbrpc   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("smdbrpc/protos/smdbrpc.proto", fileDescriptor_smdbrpc_ab625d982200c379)
}

var fileDescriptor_smdbrpc_ab625d982200c379 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcf, 0xaa, 0xda, 0x40,
	0x14, 0x87, 0x33, 0x46, 0x5b, 0x39, 0x89, 0x58, 0x86, 0xb6, 0x88, 0x94, 0x69, 0x9a, 0x55, 0x36,
	0xd5, 0x12, 0xba, 0xe9, 0xb6, 0x52, 0x2a, 0xe8, 0xa2, 0x0c, 0x45, 0x4a, 0x37, 0x32, 0x26, 0xd3,
	0x3a, 0x98, 0x98, 0x34, 0x33, 0xd6, 0x9b, 0xb7, 0xb8, 0xaf, 0x70, 0xdf, 0xc6, 0xa5, 0x4b, 0x97,
	0xf7, 0xc6, 0x17, 0xb9, 0x38, 0x31, 0xfe, 0x81, 0xcb, 0xdd, 0xcd, 0xef, 0x9c, 0xef, 0x1c, 0xbe,
	0x39, 0xf0, 0x4e, 0xc6, 0xe1, 0x2c, 0x4b, 0x83, 0x7e, 0x9a, 0x25, 0x2a, 0x91, 0xfd, 0x63, 0xec,
	0xe9, 0x88, 0x5f, 0x1e, 0xa3, 0x3b, 0x06, 0x7b, 0x38, 0x1e, 0xfc, 0x14, 0x31, 0x97, 0x8a, 0xc5,
	0x29, 0xee, 0x42, 0x73, 0xcd, 0xa2, 0x48, 0x89, 0x98, 0x77, 0x90, 0x83, 0x3c, 0x93, 0x9e, 0x32,
	0x76, 0xc0, 0x8a, 0x92, 0xbf, 0x22, 0x60, 0x65, 0xbb, 0xe6, 0x20, 0xaf, 0x41, 0x2f, 0x4b, 0xee,
	0x27, 0x78, 0x31, 0x9a, 0xfc, 0x60, 0x22, 0xc3, 0xaf, 0xc0, 0x5c, 0xf0, 0x5c, 0xaf, 0xa8, 0xd3,
	0xc3, 0x13, 0xbf, 0x86, 0xc6, 0x7f, 0x16, 0xad, 0xca, 0xb9, 0x3a, 0x2d, 0x83, 0x7b, 0x87, 0xa0,
	0x3d, 0x4c, 0x94, 0x9c, 0xb3, 0x2c, 0xa4, 0xfc, 0xdf, 0x8a, 0x4b, 0x85, 0xbf, 0x80, 0x3d, 0x8f,
	0x02, 0x55, 0x39, 0xe9, 0x25, 0x96, 0xff, 0xa6, 0x57, 0x7d, 0xe1, 0x52, 0x98, 0x5e, 0xa1, 0xd8,
	0x07, 0x7b, 0x9d, 0x09, 0xc5, 0xa7, 0x0b, 0x9e, 0x4b, 0xae, 0x3a, 0x35, 0xc7, 0xf4, 0x2c, 0xbf,
	0x7d, 0x1a, 0x2d, 0xed, 0xa8, 0xa5, 0xa1, 0x91, 0x66, 0xf0, 0x7b, 0xb0, 0x32, 0xce, 0xc2, 0x6a,
	0xc4, 0x74, 0x4c, 0xaf, 0x4e, 0xe1, 0x50, 0x2a, 0x01, 0x77, 0x0e, 0xad, 0xb3, 0x62, 0x1a, 0xe5,
	0xf8, 0x03, 0xd8, 0x42, 0x4e, 0x83, 0x24, 0x8e, 0x85, 0x52, 0x3c, 0xd4, 0x82, 0x4d, 0x6a, 0x09,
	0x39, 0xa8, 0x4a, 0xf8, 0x33, 0xb4, 0xf4, 0x52, 0xfd, 0xcb, 0x67, 0x4c, 0xec, 0x03, 0x35, 0x39,
	0x42, 0xfe, 0xaf, 0xf3, 0x31, 0xbe, 0x33, 0xc5, 0xd7, 0x2c, 0xc7, 0xdf, 0xa0, 0x3d, 0x48, 0x96,
	0x8a, 0x05, 0xaa, 0xea, 0xe0, 0xce, 0xf9, 0x12, 0xd7, 0x97, 0xeb, 0xbe, 0x7d, 0xa2, 0x93, 0x46,
	0xb9, 0x6b, 0x7c, 0xfd, 0xb8, 0x79, 0x20, 0xc6, 0xa6, 0x20, 0x68, 0x5b, 0x10, 0xb4, 0x2b, 0x08,
	0xba, 0x2f, 0x08, 0xba, 0xdd, 0x13, 0x63, 0xbb, 0x27, 0xc6, 0x6e, 0x4f, 0x8c, 0xdf, 0x16, 0xbf,
	0xe1, 0x81, 0x58, 0xfe, 0xc9, 0x58, 0x3a, 0x7b, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x66, 0xdd, 0x6d,
	0x40, 0x3e, 0x02, 0x00, 0x00,
}
